
#include "VertexLayoutCommon.h"

static UINT OFFSET_POSITION = 0;
static UINT OFFSET_COLOR = OFFSET_POSITION + sizeof(DirectX::XMFLOAT3);
static UINT OFFSET_TEXCOORD = OFFSET_COLOR + sizeof(DirectX::XMFLOAT4);
static UINT OFFSET_NORMAL = OFFSET_TEXCOORD + sizeof(DirectX::XMFLOAT2);
static UINT OFFSET_TANGENT = OFFSET_NORMAL + sizeof(DirectX::XMFLOAT3);

D3D11_INPUT_ELEMENT_DESC UNIVERSAL_INPUT_LAYOUT[5] = {
	{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, OFFSET_POSITION, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "COLOR", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, OFFSET_COLOR, D3D11_INPUT_PER_VERTEX_DATA, 0},
	{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, OFFSET_TEXCOORD, D3D11_INPUT_PER_VERTEX_DATA, 0},
	{ "NORMAL", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, OFFSET_NORMAL, D3D11_INPUT_PER_VERTEX_DATA, 0},
	{ "TANGENT", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, OFFSET_TANGENT, D3D11_INPUT_PER_VERTEX_DATA, 0},
};